package com.sheepdog.dal.entities;

// Generated 13.12.2013 11:09:05 by Hibernate Tools 4.0.0

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubscriptionEntity generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIPTION")
public class SubscriptionEntity extends GenericDalEntity<Integer> implements java.io.Serializable {
	private static final long serialVersionUID = -5934848559501170236L;
	private UserEntity userEntity;
	private FileEntity fileEntity;

	public SubscriptionEntity() {
	}

	public SubscriptionEntity(UserEntity userEntity, FileEntity fileEntity) {
		this.userEntity = userEntity;
		this.fileEntity = fileEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILE_ID", nullable = false)
	public FileEntity getFileEntity() {
		return this.fileEntity;
	}

	public void setFileEntity(FileEntity fileEntity) {
		this.fileEntity = fileEntity;
	}

}
