package com.sheepdog.dal.entities;

// Generated 10.12.2013 11:02:02 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubscriptionEntity generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIPTION", schema = "PUBLIC", catalog = "PUBLIC")
public class SubscriptionEntity implements java.io.Serializable {

	private Integer id;
	private UserEntity userEntity;
	private FileEntity fileEntity;

	public SubscriptionEntity() {
	}

	public SubscriptionEntity(UserEntity userEntity, FileEntity fileEntity) {
		this.userEntity = userEntity;
		this.fileEntity = fileEntity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILE_ID", nullable = false)
	public FileEntity getFileEntity() {
		return this.fileEntity;
	}

	public void setFileEntity(FileEntity fileEntity) {
		this.fileEntity = fileEntity;
	}

}
