package com.sheepdog.dal.entities;

// Generated 10.12.2013 11:02:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FileEntity generated by hbm2java
 */
@Entity
@Table(name = "FILE", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = @UniqueConstraint(columnNames = "QUALIFIED_NAME"))
public class FileEntity implements java.io.Serializable {

	private Integer id;
	private ProjectEntity projectEntity;
	private RevisionEntity revisionEntity;
	private String name;
	private String qualifiedName;
	private String creatorName;
	private Set<SubscriptionEntity> subscriptionEntities = new HashSet<SubscriptionEntity>(
			0);

	public FileEntity() {
	}

	public FileEntity(ProjectEntity projectEntity,
			RevisionEntity revisionEntity, String name, String qualifiedName,
			String creatorName) {
		this.projectEntity = projectEntity;
		this.revisionEntity = revisionEntity;
		this.name = name;
		this.qualifiedName = qualifiedName;
		this.creatorName = creatorName;
	}

	public FileEntity(ProjectEntity projectEntity,
			RevisionEntity revisionEntity, String name, String qualifiedName,
			String creatorName, Set<SubscriptionEntity> subscriptionEntities) {
		this.projectEntity = projectEntity;
		this.revisionEntity = revisionEntity;
		this.name = name;
		this.qualifiedName = qualifiedName;
		this.creatorName = creatorName;
		this.subscriptionEntities = subscriptionEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public ProjectEntity getProjectEntity() {
		return this.projectEntity;
	}

	public void setProjectEntity(ProjectEntity projectEntity) {
		this.projectEntity = projectEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REVISION_ID", nullable = false)
	public RevisionEntity getRevisionEntity() {
		return this.revisionEntity;
	}

	public void setRevisionEntity(RevisionEntity revisionEntity) {
		this.revisionEntity = revisionEntity;
	}

	@Column(name = "NAME", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "QUALIFIED_NAME", unique = true, nullable = false)
	public String getQualifiedName() {
		return this.qualifiedName;
	}

	public void setQualifiedName(String qualifiedName) {
		this.qualifiedName = qualifiedName;
	}

	@Column(name = "CREATOR_NAME", nullable = false, length = 128)
	public String getCreatorName() {
		return this.creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fileEntity")
	public Set<SubscriptionEntity> getSubscriptionEntities() {
		return this.subscriptionEntities;
	}

	public void setSubscriptionEntities(
			Set<SubscriptionEntity> subscriptionEntities) {
		this.subscriptionEntities = subscriptionEntities;
	}

}
