package com.sheepdog.dal.entities;

// Generated 10.12.2013 11:02:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = {
		@UniqueConstraint(columnNames = "EMAIL"),
		@UniqueConstraint(columnNames = "LOGIN") })
public class UserEntity implements java.io.Serializable {

	private Integer id;
	private String login;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private Set<SubscriptionEntity> subscriptionEntities = new HashSet<SubscriptionEntity>(
			0);
	private Set<ProjectEntity> projectEntities = new HashSet<ProjectEntity>(0);

	public UserEntity() {
	}

	public UserEntity(String login, String firstName, String lastName,
			String email, String password) {
		this.login = login;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
	}

	public UserEntity(String login, String firstName, String lastName,
			String email, String password,
			Set<SubscriptionEntity> subscriptionEntities,
			Set<ProjectEntity> projectEntities) {
		this.login = login;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.subscriptionEntities = subscriptionEntities;
		this.projectEntities = projectEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "LOGIN", unique = true, nullable = false, length = 128)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 128)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 256)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", unique = true, nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 2048)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userEntity")
	public Set<SubscriptionEntity> getSubscriptionEntities() {
		return this.subscriptionEntities;
	}

	public void setSubscriptionEntities(
			Set<SubscriptionEntity> subscriptionEntities) {
		this.subscriptionEntities = subscriptionEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userEntity")
	public Set<ProjectEntity> getProjectEntities() {
		return this.projectEntities;
	}

	public void setProjectEntities(Set<ProjectEntity> projectEntities) {
		this.projectEntities = projectEntities;
	}

}
